const router = require("express").Router();
const auth = require("../../middleware/auth");
const role = require("../../middleware/role");
const controller = require("../../controllers/admin/admin.controller");
const ticketsController = require("../../controllers/admin/admin.tickets.controller");
router.use(auth, role("admin"));
router.use("/services", require("../service/service.routes").adminRouter);
router.use("/provider-applications", require("./provider-applications.routes"));
router.get("/dashboard", controller.dashboard);
router.get("/bookings", controller.bookings);
router.get("/bookings/:id/available-providers", controller.availableProviders);
router.post("/bookings/:id/assign", controller.assignProvider);
router.get("/jobs", controller.jobs);
router.patch("/jobs/:id/status", controller.updateJobStatus);
router.get("/users", controller.users);
router.get("/tickets", ticketsController.list);
router.patch("/tickets/:id", ticketsController.respond);
module.exports = router;
